title: Configuration
type: object
properties:
  invalidateApiKeyAfter:
    type: integer
    default: 86400
  messagingCenterEnabled:
    type: boolean
    default: true
  theme:
    type: integer
    description: Links to the id of an existing theme
description: The configuration of jinya
x-tags:
  - maintenance
